#!/bin/bash
# Manual pg_duckdb installation script for PostgreSQL container
# This script provides instructions for installing pg_duckdb in the PostgreSQL container

echo "======================================================================"
echo "pg_duckdb Manual Installation Guide"
echo "======================================================================"
echo ""
echo "Since the PostgreSQL container is Alpine Linux, you need to install"
echo "pg_duckdb manually. Here are your options:"
echo ""
echo "======================================================================"
echo "OPTION 1: Install via apk (Alpine package manager)"
echo "======================================================================"
echo ""
echo "Run these commands in the PostgreSQL container:"
echo ""
echo "  docker compose exec postgres ash"
echo "  apk add --no-cache postgresql-17-pg-duckdb"
echo "  exit"
echo ""
echo "Then restart PostgreSQL:"
echo "  docker compose restart postgres"
echo ""
echo "======================================================================"
echo "OPTION 2: Install via pgxman (if available in container)"
echo "======================================================================"
echo ""
echo "Run these commands in the PostgreSQL container:"
echo ""
echo "  docker compose exec postgres bash"
echo "  pgxman install --pg 17 pg_duckdb"
echo "  exit"
echo ""
echo "Then restart PostgreSQL:"
echo "  docker compose restart postgres"
echo ""
echo "======================================================================"
echo "OPTION 3: Build from source (most reliable)"
echo "======================================================================"
echo ""
echo "Run these commands in the PostgreSQL container:"
echo ""
echo "  docker compose exec postgres ash"
echo ""
echo "  # Install build dependencies"
echo "  apk add --no-cache build-base git postgresql17-dev"
echo ""
echo "  # Clone pg_duckdb repository"
echo "  cd /tmp"
echo "  git clone https://github.com/duckdb/pg_duckdb.git"
echo "  cd pg_duckdb"
echo ""
echo "  # Build and install"
echo "  make install"
echo ""
echo "  # Exit container"
echo "  exit"
echo ""
echo "Then restart PostgreSQL:"
echo "  docker compose restart postgres"
echo ""
echo "======================================================================"
echo "After installation, verify pg_duckdb is installed:"
echo "======================================================================"
echo ""
echo "  docker compose exec postgres psql -U postgres -d nyc_taxi -c \\"
echo "    \"SELECT * FROM pg_extension WHERE extname = 'pg_duckdb';\""
echo ""
echo "======================================================================"
echo "Then run the pg_duckdb tests:"
echo "======================================================================"
echo ""
echo "  cd analytical-db-knockout"
echo "  make test-pg-duckdb"
echo ""
echo "======================================================================"